import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class MainWindowForm {
  private JPanel mainPanel;
  private JTextArea teilnehmerTextArea;
  private JLabel teilnehmerLabel;
  private JButton teilnehmerSpeichernButton;
  private JPanel teilnehmerPanel;
  private JButton generierenButton;
  private JPanel dataPanel;
  private JTextField klasseTextField;
  private JTextField trainerTextField;
  private JTextField lernfeldTextField;
  private JTextField berichtNrTextField;
  private JTextField jahrTextField;
  private JTextField wocheTextField;
  private JTextArea moTextArea;
  private JTextArea diTextArea;
  private JTextArea miTextArea;
  private JTextArea doTextArea;
  private JTextArea frTextArea;
  private JScrollPane teilnehmerScrollPane;
  private JLabel klasseLabel;
  private JLabel jahrLabel;
  private JLabel trainerLabel;
  private JLabel lernfeldLabel;
  private JLabel berichtNrLabel;
  private JLabel wocheLabel;
  private JScrollPane daysScrollPane;
  private JPanel daysPanel;
  private JLabel moLabel;
  private JLabel diLabel;
  private JLabel miLabel;
  private JLabel doLabel;
  private JLabel frLabel;

  public JPanel getMainPanel() {
    return mainPanel;
  }

  public JTextArea getTeilnehmerTextArea() {
    return teilnehmerTextArea;
  }

  public JLabel getTeilnehmerLabel() {
    return teilnehmerLabel;
  }

  public JButton getTeilnehmerSpeichernButton() {
    return teilnehmerSpeichernButton;
  }

  public JPanel getTeilnehmerPanel() {
    return teilnehmerPanel;
  }

  public JButton getGenerierenButton() {
    return generierenButton;
  }

  public JPanel getDataPanel() {
    return dataPanel;
  }

  public JTextField getKlasseTextField() {
    return klasseTextField;
  }

  public JTextField getTrainerTextField() {
    return trainerTextField;
  }

  public JTextField getLernfeldTextField() {
    return lernfeldTextField;
  }

  public JTextField getBerichtNrTextField() {
    return berichtNrTextField;
  }

  public JTextField getJahrTextField() {
    return jahrTextField;
  }

  public JTextField getWocheTextField() {
    return wocheTextField;
  }

  public JTextArea getMoTextArea() {
    return moTextArea;
  }

  public JTextArea getDiTextArea() {
    return diTextArea;
  }

  public JTextArea getMiTextArea() {
    return miTextArea;
  }

  public JTextArea getDoTextArea() {
    return doTextArea;
  }

  public JTextArea getFrTextArea() {
    return frTextArea;
  }

  public JScrollPane getTeilnehmerScrollPane() {
    return teilnehmerScrollPane;
  }

  public JLabel getKlasseLabel() {
    return klasseLabel;
  }

  public JLabel getJahrLabel() {
    return jahrLabel;
  }

  public JLabel getTrainerLabel() {
    return trainerLabel;
  }

  public JLabel getLernfeldLabel() {
    return lernfeldLabel;
  }

  public JLabel getBerichtNrLabel() {
    return berichtNrLabel;
  }

  public JLabel getWocheLabel() {
    return wocheLabel;
  }

  public JScrollPane getDaysScrollPane() {
    return daysScrollPane;
  }

  public JPanel getDaysPanel() {
    return daysPanel;
  }

  public JLabel getMoLabel() {
    return moLabel;
  }

  public JLabel getDiLabel() {
    return diLabel;
  }

  public JLabel getMiLabel() {
    return miLabel;
  }

  public JLabel getDoLabel() {
    return doLabel;
  }

  public JLabel getFrLabel() {
    return frLabel;
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    mainPanel = new JPanel();
    mainPanel.setLayout(new BorderLayout(5, 5));
    mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
    teilnehmerPanel = new JPanel();
    teilnehmerPanel.setLayout(new BorderLayout(0, 0));
    teilnehmerPanel.setDoubleBuffered(true);
    teilnehmerPanel.setEnabled(true);
    mainPanel.add(teilnehmerPanel, BorderLayout.WEST);
    teilnehmerLabel = new JLabel();
    teilnehmerLabel.setHorizontalAlignment(0);
    teilnehmerLabel.setText("Teilnehmer");
    teilnehmerLabel.setVerticalAlignment(0);
    teilnehmerPanel.add(teilnehmerLabel, BorderLayout.NORTH);
    teilnehmerSpeichernButton = new JButton();
    teilnehmerSpeichernButton.setAlignmentX(0.0f);
    teilnehmerSpeichernButton.setText("Teilnehmer speichern");
    teilnehmerPanel.add(teilnehmerSpeichernButton, BorderLayout.SOUTH);
    teilnehmerScrollPane = new JScrollPane();
    teilnehmerPanel.add(teilnehmerScrollPane, BorderLayout.CENTER);
    teilnehmerTextArea = new JTextArea();
    teilnehmerScrollPane.setViewportView(teilnehmerTextArea);
    generierenButton = new JButton();
    generierenButton.setText("Generieren");
    mainPanel.add(generierenButton, BorderLayout.SOUTH);
    dataPanel = new JPanel();
    dataPanel.setLayout(new GridBagLayout());
    dataPanel.setAlignmentX(0.0f);
    dataPanel.setAlignmentY(0.0f);
    dataPanel.setEnabled(true);
    Font dataPanelFont = this.$$$getFont$$$(null, -1, -1, dataPanel.getFont());
    if (dataPanelFont != null) dataPanel.setFont(dataPanelFont);
    dataPanel.setMaximumSize(new Dimension(214, 214));
    mainPanel.add(dataPanel, BorderLayout.EAST);
    klasseLabel = new JLabel();
    klasseLabel.setText("Klasse");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.SOUTH;
    dataPanel.add(klasseLabel, gbc);
    klasseTextField = new JTextField();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    dataPanel.add(klasseTextField, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 12;
    gbc.weighty = 10.0;
    gbc.fill = GridBagConstraints.VERTICAL;
    dataPanel.add(spacer1, gbc);
    jahrLabel = new JLabel();
    jahrLabel.setText("Jahr");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 6;
    gbc.anchor = GridBagConstraints.SOUTH;
    dataPanel.add(jahrLabel, gbc);
    jahrTextField = new JTextField();
    jahrTextField.setColumns(10);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 7;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    dataPanel.add(jahrTextField, gbc);
    trainerLabel = new JLabel();
    trainerLabel.setAlignmentY(0.0f);
    trainerLabel.setText("Trainer");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.SOUTH;
    dataPanel.add(trainerLabel, gbc);
    trainerTextField = new JTextField();
    trainerTextField.setColumns(10);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    dataPanel.add(trainerTextField, gbc);
    lernfeldLabel = new JLabel();
    lernfeldLabel.setText("Lernfeld");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    dataPanel.add(lernfeldLabel, gbc);
    lernfeldTextField = new JTextField();
    lernfeldTextField.setColumns(10);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 5;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    dataPanel.add(lernfeldTextField, gbc);
    berichtNrLabel = new JLabel();
    berichtNrLabel.setText("Bericht-Nr");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 8;
    dataPanel.add(berichtNrLabel, gbc);
    berichtNrTextField = new JTextField();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 9;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    dataPanel.add(berichtNrTextField, gbc);
    wocheLabel = new JLabel();
    wocheLabel.setText("Von - bis");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 10;
    gbc.anchor = GridBagConstraints.SOUTH;
    dataPanel.add(wocheLabel, gbc);
    wocheTextField = new JTextField();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 11;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    dataPanel.add(wocheTextField, gbc);
    daysScrollPane = new JScrollPane();
    mainPanel.add(daysScrollPane, BorderLayout.CENTER);
    daysPanel = new JPanel();
    daysPanel.setLayout(new GridBagLayout());
    daysScrollPane.setViewportView(daysPanel);
    moLabel = new JLabel();
    moLabel.setText("Mo:");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.WEST;
    daysPanel.add(moLabel, gbc);
    moTextArea = new JTextArea();
    moTextArea.setColumns(0);
    moTextArea.setRows(5);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.BOTH;
    daysPanel.add(moTextArea, gbc);
    diLabel = new JLabel();
    diLabel.setText("Di:");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    daysPanel.add(diLabel, gbc);
    diTextArea = new JTextArea();
    diTextArea.setRequestFocusEnabled(true);
    diTextArea.setRows(5);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.BOTH;
    daysPanel.add(diTextArea, gbc);
    miLabel = new JLabel();
    miLabel.setText("Mi:");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    gbc.anchor = GridBagConstraints.WEST;
    daysPanel.add(miLabel, gbc);
    miTextArea = new JTextArea();
    miTextArea.setRows(5);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 5;
    gbc.fill = GridBagConstraints.BOTH;
    daysPanel.add(miTextArea, gbc);
    doLabel = new JLabel();
    doLabel.setText("Do:");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 6;
    gbc.anchor = GridBagConstraints.WEST;
    daysPanel.add(doLabel, gbc);
    doTextArea = new JTextArea();
    doTextArea.setRows(5);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 7;
    gbc.fill = GridBagConstraints.BOTH;
    daysPanel.add(doTextArea, gbc);
    frLabel = new JLabel();
    frLabel.setText("Fr:");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 8;
    gbc.anchor = GridBagConstraints.WEST;
    daysPanel.add(frLabel, gbc);
    frTextArea = new JTextArea();
    frTextArea.setRows(5);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 9;
    gbc.fill = GridBagConstraints.BOTH;
    daysPanel.add(frTextArea, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    daysPanel.add(spacer2, gbc);
  }

  /**
   * @noinspection ALL
   */
  private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
    if (currentFont == null) return null;
    String resultName;
    if (fontName == null) {
      resultName = currentFont.getName();
    } else {
      Font testFont = new Font(fontName, Font.PLAIN, 10);
      if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
        resultName = fontName;
      } else {
        resultName = currentFont.getName();
      }
    }
    Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
    Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
    return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }
}
